# MYSQL default.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-config
  namespace: mysql
data:
  custom.cnf: |-
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    default-storage-engine=INNODB
    max_allowed_packet=256M
    max_connections=300
    #innodb_log_file_size=2GB
    #transaction-isolation=READ-COMMITTED
    sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    innodb_buffer_pool_size=1G
