apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: mysql
  labels:
    type: local
spec:
  storageClassName: nfs-client
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/mysql/
    server: <nfs-server ip or domain>
