apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
  labels:
    app: mysql
type: Opaque
data:
  DB_USERNAME: c29tYXoK # echo -n "somaz" | base64
  DB_PASSWORD: c29tYXoK # echo -n "somaz" | base64
  DB_ROOT_PASSWORD: c29tYXoK # echo -n "somaz" | base64
