apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-db-pv
  namespace: mongo-db
  labels:
    type: local
spec:
  storageClassName: nfs-client
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/mongo/
    server: <nfs-server ip or domain>
