apiVersion: v1
kind: Service
metadata:
  name: mongo-db
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30017 # # Write down the port you want
      protocol: TCP
  selector:
    app: mongo-db
