apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  DB_USERNAME: bW9uZ28= # echo -n "mongo" | base64
  DB_PASSWORD: bW9uZ28= # echo -n "mongo" | base64
