apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo:latest
          name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: DB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 27017
              protocol: TCP
              name: mongodb
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          securityContext:
            runAsUser: 1001  # nerdystar 사용자의 UID
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: nfs-mongodb-pvc
