apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  DB_USERNAME: bW9uZ28K # echo "mongo" | base64
  DB_PASSWORD: bW9uZ28K # echo "mongo" | base64
