apiVersion: v1
kind: Service
metadata:
  name: mongodb
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"mongo-db-backend-config"}}'
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
